### ISSUE TITLE
Make Error: Permission Denied

### ISSUE THREAD

**Issue by DevonKerins** [PSUmodeling/MM-PIHM#22]
I just tried to compile the model version 1.0.0-rc1 and have gotten the following error:
![make_error_09_02_2020](https://user-images.githubusercontent.com/70672312/92051736-f7e45f80-ed5a-11ea-8064-bc385020af39.JPG)

**Comment by shiyuning** [comment]
Could you please try this in your MM-PIHM directory, and then make again?

```bash
chmod 755 util/check_latest_vers.sh
```

**Comment by DevonKerins** [comment]
Thanks Yuning, that worked.
