### ISSUE TITLE
Output file format

### ISSUE THREAD

**Issue by KayalvizhiSadayappan** [PSUmodeling/MM-PIHM#23]
This is not a bug. In this version, the format output files are saved has been changed back to the format used in much earlier versions but the format of the previous version (one just before this version) where we had different fluxes (overland, lateral, groundwater) in same file is much easier to work with for analysis.

**Comment by shiyuning** [comment]
How did you compile? Did you use TGM=on or LUMPED=on?

**Comment by KayalvizhiSadayappan** [comment]
I used DGW=on TGM=on flux-pihm

**Comment by shiyuning** [comment]
TGM is no longer supported. Please use LUMPED=on. See the manual and release note for details.
