### ISSUE TITLE
What QGIS version can be used to adapt the plug-in pihmgis

### ISSUE THREAD

**Issue by Liuhexin6688** [PSUmodeling/MM-PIHM#30]
There is no version suggestion in the official website instruction manual. I tried several versions that are incompatible，such as QGIS3.26,QGIS.22,QGIS2.2.0,QGIS2.6,QGIS2.8

**Comment by shiyuning** [comment]
Unfortunately, I did not develop PIHMgis and I don't know which version of QGIS it would be compatible with. I suggest you contact the developer of PIHMgis (https://github.com/gopal-bhatt/PIHMgis), Gopal Bhatt, who should be able to provide you with some guidance.
